name: setup-verilator
description: Setup verilator on GitHub Actions runners
author: 'Naoya Hatta'
branding:
  color: green
  icon: download
inputs:
  version:
    description: Version of Verilator to install
    required: false
    default: latest
runs:
  using: node20
  main: dist/index.js
